/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SupplierId = IDL.Nat;
export const MitigationStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const MitigationAction = IDL.Record({
  'id' : IDL.Nat,
  'status' : MitigationStatus,
  'action' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'updatedAt' : Timestamp,
  'supplierId' : SupplierId,
});
export const RiskScore = IDL.Nat;
export const PortfolioRiskSnapshot = IDL.Record({
  'totalSuppliers' : IDL.Nat,
  'avgCompositeRisk' : IDL.Nat,
  'maxRiskSupplierId' : SupplierId,
  'portfolioRiskScore' : IDL.Nat,
  'lowRiskCount' : IDL.Nat,
  'maxRiskScore' : RiskScore,
  'mediumRiskCount' : IDL.Nat,
  'highRiskCount' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const SupplierCategory = IDL.Variant({
  'Chemicals' : IDL.Null,
  'RawMaterials' : IDL.Null,
  'Packaging' : IDL.Null,
  'Logistics' : IDL.Null,
  'Services' : IDL.Null,
  'Electronics' : IDL.Null,
  'Manufacturing' : IDL.Null,
});
export const SupplierTier = IDL.Variant({
  'Tier1' : IDL.Null,
  'Tier2' : IDL.Null,
  'Tier3' : IDL.Null,
});
export const AlternativeSupplier = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'tier' : SupplierTier,
  'compositeRisk' : RiskScore,
  'avgLeadTimeDays' : IDL.Nat,
  'category' : SupplierCategory,
  'supplierId' : SupplierId,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const RiskAlert = IDL.Record({
  'qualityRisk' : RiskScore,
  'delayRisk' : RiskScore,
  'supplierName' : IDL.Text,
  'compositeRisk' : RiskScore,
  'triggeredAt' : Timestamp,
  'failureRisk' : RiskScore,
  'riskLevel' : RiskLevel,
  'supplierId' : SupplierId,
});
export const SupplierProfile = IDL.Record({
  'id' : SupplierId,
  'carrierPerformanceScore' : IDL.Float64,
  'defectRate' : IDL.Float64,
  'dependsOn' : IDL.Vec(SupplierId),
  'qualityRisk' : IDL.Nat,
  'yearsActive' : IDL.Nat,
  'delayRisk' : IDL.Nat,
  'name' : IDL.Text,
  'onTimeDeliveryRate' : IDL.Float64,
  'tier' : SupplierTier,
  'volumeHandled' : IDL.Nat,
  'compositeRisk' : IDL.Nat,
  'equipmentFailureRate' : IDL.Float64,
  'avgLeadTimeDays' : IDL.Nat,
  'category' : SupplierCategory,
  'supplyInterruptionCount' : IDL.Nat,
  'failureRisk' : IDL.Nat,
  'location' : IDL.Text,
});
export const RiskTrendEntry = IDL.Record({
  'qualityRisk' : RiskScore,
  'delayRisk' : RiskScore,
  'compositeRisk' : RiskScore,
  'timestamp' : Timestamp,
  'failureRisk' : RiskScore,
});
export const NetworkNode = IDL.Record({
  'dependsOn' : IDL.Vec(SupplierId),
  'supplierName' : IDL.Text,
  'tier' : SupplierTier,
  'compositeRisk' : RiskScore,
  'category' : SupplierCategory,
  'supplierId' : SupplierId,
});
export const SupplyNetworkGraph = IDL.Record({
  'edgeCount' : IDL.Nat,
  'nodes' : IDL.Vec(NetworkNode),
});
export const DisruptionType = IDL.Variant({
  'QualityFailure' : IDL.Null,
  'LogisticsDelay' : IDL.Null,
  'SupplyInterruption' : IDL.Null,
  'NaturalDisaster' : IDL.Null,
  'EquipmentFailure' : IDL.Null,
});
export const DisruptionImpact = IDL.Record({
  'estimatedRecoveryDays' : IDL.Nat,
  'cascadingSupplierIds' : IDL.Vec(SupplierId),
  'affectedSupplierId' : SupplierId,
  'directRiskIncrease' : IDL.Nat,
  'disruptionType' : DisruptionType,
  'portfolioRiskDelta' : IDL.Int,
  'severity' : RiskLevel,
});
export const SupplierMetricsUpdate = IDL.Record({
  'carrierPerformanceScore' : IDL.Opt(IDL.Float64),
  'defectRate' : IDL.Opt(IDL.Float64),
  'onTimeDeliveryRate' : IDL.Opt(IDL.Float64),
  'volumeHandled' : IDL.Opt(IDL.Nat),
  'equipmentFailureRate' : IDL.Opt(IDL.Float64),
  'avgLeadTimeDays' : IDL.Opt(IDL.Nat),
  'supplyInterruptionCount' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'computeDelayRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
  'computeFailureRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
  'computeQualityRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
  'getCompositeRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
  'getMitigationActions' : IDL.Func(
      [SupplierId],
      [IDL.Vec(MitigationAction)],
      ['query'],
    ),
  'getPortfolioRiskSnapshot' : IDL.Func([], [PortfolioRiskSnapshot], ['query']),
  'getRecommendedAlternatives' : IDL.Func(
      [SupplierId, SupplierCategory],
      [IDL.Vec(AlternativeSupplier)],
      ['query'],
    ),
  'getRiskAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(RiskAlert)], ['query']),
  'getSupplierProfiles' : IDL.Func([], [IDL.Vec(SupplierProfile)], ['query']),
  'getSupplierTrendHistory' : IDL.Func(
      [SupplierId, IDL.Nat],
      [IDL.Vec(RiskTrendEntry)],
      ['query'],
    ),
  'getSupplyNetworkGraph' : IDL.Func([], [SupplyNetworkGraph], ['query']),
  'logMitigationAction' : IDL.Func(
      [SupplierId, IDL.Text, Timestamp],
      [IDL.Nat],
      [],
    ),
  'simulateDisruption' : IDL.Func(
      [SupplierId, DisruptionType],
      [DisruptionImpact],
      ['query'],
    ),
  'updateSupplierMetrics' : IDL.Func(
      [SupplierId, SupplierMetricsUpdate],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SupplierId = IDL.Nat;
  const MitigationStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const MitigationAction = IDL.Record({
    'id' : IDL.Nat,
    'status' : MitigationStatus,
    'action' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : Timestamp,
    'updatedAt' : Timestamp,
    'supplierId' : SupplierId,
  });
  const RiskScore = IDL.Nat;
  const PortfolioRiskSnapshot = IDL.Record({
    'totalSuppliers' : IDL.Nat,
    'avgCompositeRisk' : IDL.Nat,
    'maxRiskSupplierId' : SupplierId,
    'portfolioRiskScore' : IDL.Nat,
    'lowRiskCount' : IDL.Nat,
    'maxRiskScore' : RiskScore,
    'mediumRiskCount' : IDL.Nat,
    'highRiskCount' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const SupplierCategory = IDL.Variant({
    'Chemicals' : IDL.Null,
    'RawMaterials' : IDL.Null,
    'Packaging' : IDL.Null,
    'Logistics' : IDL.Null,
    'Services' : IDL.Null,
    'Electronics' : IDL.Null,
    'Manufacturing' : IDL.Null,
  });
  const SupplierTier = IDL.Variant({
    'Tier1' : IDL.Null,
    'Tier2' : IDL.Null,
    'Tier3' : IDL.Null,
  });
  const AlternativeSupplier = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'tier' : SupplierTier,
    'compositeRisk' : RiskScore,
    'avgLeadTimeDays' : IDL.Nat,
    'category' : SupplierCategory,
    'supplierId' : SupplierId,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const RiskAlert = IDL.Record({
    'qualityRisk' : RiskScore,
    'delayRisk' : RiskScore,
    'supplierName' : IDL.Text,
    'compositeRisk' : RiskScore,
    'triggeredAt' : Timestamp,
    'failureRisk' : RiskScore,
    'riskLevel' : RiskLevel,
    'supplierId' : SupplierId,
  });
  const SupplierProfile = IDL.Record({
    'id' : SupplierId,
    'carrierPerformanceScore' : IDL.Float64,
    'defectRate' : IDL.Float64,
    'dependsOn' : IDL.Vec(SupplierId),
    'qualityRisk' : IDL.Nat,
    'yearsActive' : IDL.Nat,
    'delayRisk' : IDL.Nat,
    'name' : IDL.Text,
    'onTimeDeliveryRate' : IDL.Float64,
    'tier' : SupplierTier,
    'volumeHandled' : IDL.Nat,
    'compositeRisk' : IDL.Nat,
    'equipmentFailureRate' : IDL.Float64,
    'avgLeadTimeDays' : IDL.Nat,
    'category' : SupplierCategory,
    'supplyInterruptionCount' : IDL.Nat,
    'failureRisk' : IDL.Nat,
    'location' : IDL.Text,
  });
  const RiskTrendEntry = IDL.Record({
    'qualityRisk' : RiskScore,
    'delayRisk' : RiskScore,
    'compositeRisk' : RiskScore,
    'timestamp' : Timestamp,
    'failureRisk' : RiskScore,
  });
  const NetworkNode = IDL.Record({
    'dependsOn' : IDL.Vec(SupplierId),
    'supplierName' : IDL.Text,
    'tier' : SupplierTier,
    'compositeRisk' : RiskScore,
    'category' : SupplierCategory,
    'supplierId' : SupplierId,
  });
  const SupplyNetworkGraph = IDL.Record({
    'edgeCount' : IDL.Nat,
    'nodes' : IDL.Vec(NetworkNode),
  });
  const DisruptionType = IDL.Variant({
    'QualityFailure' : IDL.Null,
    'LogisticsDelay' : IDL.Null,
    'SupplyInterruption' : IDL.Null,
    'NaturalDisaster' : IDL.Null,
    'EquipmentFailure' : IDL.Null,
  });
  const DisruptionImpact = IDL.Record({
    'estimatedRecoveryDays' : IDL.Nat,
    'cascadingSupplierIds' : IDL.Vec(SupplierId),
    'affectedSupplierId' : SupplierId,
    'directRiskIncrease' : IDL.Nat,
    'disruptionType' : DisruptionType,
    'portfolioRiskDelta' : IDL.Int,
    'severity' : RiskLevel,
  });
  const SupplierMetricsUpdate = IDL.Record({
    'carrierPerformanceScore' : IDL.Opt(IDL.Float64),
    'defectRate' : IDL.Opt(IDL.Float64),
    'onTimeDeliveryRate' : IDL.Opt(IDL.Float64),
    'volumeHandled' : IDL.Opt(IDL.Nat),
    'equipmentFailureRate' : IDL.Opt(IDL.Float64),
    'avgLeadTimeDays' : IDL.Opt(IDL.Nat),
    'supplyInterruptionCount' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'computeDelayRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
    'computeFailureRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
    'computeQualityRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
    'getCompositeRisk' : IDL.Func([SupplierId], [IDL.Nat], ['query']),
    'getMitigationActions' : IDL.Func(
        [SupplierId],
        [IDL.Vec(MitigationAction)],
        ['query'],
      ),
    'getPortfolioRiskSnapshot' : IDL.Func(
        [],
        [PortfolioRiskSnapshot],
        ['query'],
      ),
    'getRecommendedAlternatives' : IDL.Func(
        [SupplierId, SupplierCategory],
        [IDL.Vec(AlternativeSupplier)],
        ['query'],
      ),
    'getRiskAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(RiskAlert)], ['query']),
    'getSupplierProfiles' : IDL.Func([], [IDL.Vec(SupplierProfile)], ['query']),
    'getSupplierTrendHistory' : IDL.Func(
        [SupplierId, IDL.Nat],
        [IDL.Vec(RiskTrendEntry)],
        ['query'],
      ),
    'getSupplyNetworkGraph' : IDL.Func([], [SupplyNetworkGraph], ['query']),
    'logMitigationAction' : IDL.Func(
        [SupplierId, IDL.Text, Timestamp],
        [IDL.Nat],
        [],
      ),
    'simulateDisruption' : IDL.Func(
        [SupplierId, DisruptionType],
        [DisruptionImpact],
        ['query'],
      ),
    'updateSupplierMetrics' : IDL.Func(
        [SupplierId, SupplierMetricsUpdate],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };