/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlternativeSupplier {
  'name' : string,
  'rank' : bigint,
  'tier' : SupplierTier,
  'compositeRisk' : RiskScore,
  'avgLeadTimeDays' : bigint,
  'category' : SupplierCategory,
  'supplierId' : SupplierId,
}
export interface DisruptionImpact {
  'estimatedRecoveryDays' : bigint,
  'cascadingSupplierIds' : Array<SupplierId>,
  'affectedSupplierId' : SupplierId,
  'directRiskIncrease' : bigint,
  'disruptionType' : DisruptionType,
  'portfolioRiskDelta' : bigint,
  'severity' : RiskLevel,
}
export type DisruptionType = { 'QualityFailure' : null } |
  { 'LogisticsDelay' : null } |
  { 'SupplyInterruption' : null } |
  { 'NaturalDisaster' : null } |
  { 'EquipmentFailure' : null };
export interface MitigationAction {
  'id' : bigint,
  'status' : MitigationStatus,
  'action' : string,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'updatedAt' : Timestamp,
  'supplierId' : SupplierId,
}
export type MitigationStatus = { 'Open' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface NetworkNode {
  'dependsOn' : Array<SupplierId>,
  'supplierName' : string,
  'tier' : SupplierTier,
  'compositeRisk' : RiskScore,
  'category' : SupplierCategory,
  'supplierId' : SupplierId,
}
export interface PortfolioRiskSnapshot {
  'totalSuppliers' : bigint,
  'avgCompositeRisk' : bigint,
  'maxRiskSupplierId' : SupplierId,
  'portfolioRiskScore' : bigint,
  'lowRiskCount' : bigint,
  'maxRiskScore' : RiskScore,
  'mediumRiskCount' : bigint,
  'highRiskCount' : bigint,
  'timestamp' : Timestamp,
}
export interface RiskAlert {
  'qualityRisk' : RiskScore,
  'delayRisk' : RiskScore,
  'supplierName' : string,
  'compositeRisk' : RiskScore,
  'triggeredAt' : Timestamp,
  'failureRisk' : RiskScore,
  'riskLevel' : RiskLevel,
  'supplierId' : SupplierId,
}
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type RiskScore = bigint;
export interface RiskTrendEntry {
  'qualityRisk' : RiskScore,
  'delayRisk' : RiskScore,
  'compositeRisk' : RiskScore,
  'timestamp' : Timestamp,
  'failureRisk' : RiskScore,
}
export type SupplierCategory = { 'Chemicals' : null } |
  { 'RawMaterials' : null } |
  { 'Packaging' : null } |
  { 'Logistics' : null } |
  { 'Services' : null } |
  { 'Electronics' : null } |
  { 'Manufacturing' : null };
export type SupplierId = bigint;
export interface SupplierMetricsUpdate {
  'carrierPerformanceScore' : [] | [number],
  'defectRate' : [] | [number],
  'onTimeDeliveryRate' : [] | [number],
  'volumeHandled' : [] | [bigint],
  'equipmentFailureRate' : [] | [number],
  'avgLeadTimeDays' : [] | [bigint],
  'supplyInterruptionCount' : [] | [bigint],
}
export interface SupplierProfile {
  'id' : SupplierId,
  'carrierPerformanceScore' : number,
  'defectRate' : number,
  'dependsOn' : Array<SupplierId>,
  'qualityRisk' : bigint,
  'yearsActive' : bigint,
  'delayRisk' : bigint,
  'name' : string,
  'onTimeDeliveryRate' : number,
  'tier' : SupplierTier,
  'volumeHandled' : bigint,
  'compositeRisk' : bigint,
  'equipmentFailureRate' : number,
  'avgLeadTimeDays' : bigint,
  'category' : SupplierCategory,
  'supplyInterruptionCount' : bigint,
  'failureRisk' : bigint,
  'location' : string,
}
export type SupplierTier = { 'Tier1' : null } |
  { 'Tier2' : null } |
  { 'Tier3' : null };
export interface SupplyNetworkGraph {
  'edgeCount' : bigint,
  'nodes' : Array<NetworkNode>,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'computeDelayRisk' : ActorMethod<[SupplierId], bigint>,
  'computeFailureRisk' : ActorMethod<[SupplierId], bigint>,
  'computeQualityRisk' : ActorMethod<[SupplierId], bigint>,
  'getCompositeRisk' : ActorMethod<[SupplierId], bigint>,
  'getMitigationActions' : ActorMethod<[SupplierId], Array<MitigationAction>>,
  'getPortfolioRiskSnapshot' : ActorMethod<[], PortfolioRiskSnapshot>,
  'getRecommendedAlternatives' : ActorMethod<
    [SupplierId, SupplierCategory],
    Array<AlternativeSupplier>
  >,
  'getRiskAlerts' : ActorMethod<[bigint], Array<RiskAlert>>,
  'getSupplierProfiles' : ActorMethod<[], Array<SupplierProfile>>,
  'getSupplierTrendHistory' : ActorMethod<
    [SupplierId, bigint],
    Array<RiskTrendEntry>
  >,
  'getSupplyNetworkGraph' : ActorMethod<[], SupplyNetworkGraph>,
  'logMitigationAction' : ActorMethod<[SupplierId, string, Timestamp], bigint>,
  'simulateDisruption' : ActorMethod<
    [SupplierId, DisruptionType],
    DisruptionImpact
  >,
  'updateSupplierMetrics' : ActorMethod<
    [SupplierId, SupplierMetricsUpdate],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];