/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type RiskScore = bigint;
export interface RiskTrendEntry {
    qualityRisk: RiskScore;
    delayRisk: RiskScore;
    compositeRisk: RiskScore;
    timestamp: Timestamp;
    failureRisk: RiskScore;
}
export interface RiskAlert {
    qualityRisk: RiskScore;
    delayRisk: RiskScore;
    supplierName: string;
    compositeRisk: RiskScore;
    triggeredAt: Timestamp;
    failureRisk: RiskScore;
    riskLevel: RiskLevel;
    supplierId: SupplierId;
}
export interface SupplierMetricsUpdate {
    carrierPerformanceScore?: number;
    defectRate?: number;
    onTimeDeliveryRate?: number;
    volumeHandled?: bigint;
    equipmentFailureRate?: number;
    avgLeadTimeDays?: bigint;
    supplyInterruptionCount?: bigint;
}
export interface NetworkNode {
    dependsOn: Array<SupplierId>;
    supplierName: string;
    tier: SupplierTier;
    compositeRisk: RiskScore;
    category: SupplierCategory;
    supplierId: SupplierId;
}
export interface MitigationAction {
    id: bigint;
    status: MitigationStatus;
    action: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    updatedAt: Timestamp;
    supplierId: SupplierId;
}
export interface SupplyNetworkGraph {
    edgeCount: bigint;
    nodes: Array<NetworkNode>;
}
export interface SupplierProfile {
    id: SupplierId;
    carrierPerformanceScore: number;
    defectRate: number;
    dependsOn: Array<SupplierId>;
    qualityRisk: bigint;
    yearsActive: bigint;
    delayRisk: bigint;
    name: string;
    onTimeDeliveryRate: number;
    tier: SupplierTier;
    volumeHandled: bigint;
    compositeRisk: bigint;
    equipmentFailureRate: number;
    avgLeadTimeDays: bigint;
    category: SupplierCategory;
    supplyInterruptionCount: bigint;
    failureRisk: bigint;
    location: string;
}
export interface PortfolioRiskSnapshot {
    totalSuppliers: bigint;
    avgCompositeRisk: bigint;
    maxRiskSupplierId: SupplierId;
    portfolioRiskScore: bigint;
    lowRiskCount: bigint;
    maxRiskScore: RiskScore;
    mediumRiskCount: bigint;
    highRiskCount: bigint;
    timestamp: Timestamp;
}
export interface DisruptionImpact {
    estimatedRecoveryDays: bigint;
    cascadingSupplierIds: Array<SupplierId>;
    affectedSupplierId: SupplierId;
    directRiskIncrease: bigint;
    disruptionType: DisruptionType;
    portfolioRiskDelta: bigint;
    severity: RiskLevel;
}
export type SupplierId = bigint;
export interface AlternativeSupplier {
    name: string;
    rank: bigint;
    tier: SupplierTier;
    compositeRisk: RiskScore;
    avgLeadTimeDays: bigint;
    category: SupplierCategory;
    supplierId: SupplierId;
}
export enum DisruptionType {
    QualityFailure = "QualityFailure",
    LogisticsDelay = "LogisticsDelay",
    SupplyInterruption = "SupplyInterruption",
    NaturalDisaster = "NaturalDisaster",
    EquipmentFailure = "EquipmentFailure"
}
export enum MitigationStatus {
    Open = "Open",
    Cancelled = "Cancelled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum RiskLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum SupplierCategory {
    Chemicals = "Chemicals",
    RawMaterials = "RawMaterials",
    Packaging = "Packaging",
    Logistics = "Logistics",
    Services = "Services",
    Electronics = "Electronics",
    Manufacturing = "Manufacturing"
}
export enum SupplierTier {
    Tier1 = "Tier1",
    Tier2 = "Tier2",
    Tier3 = "Tier3"
}
export interface backendInterface {
    computeDelayRisk(supplierId: SupplierId): Promise<bigint>;
    computeFailureRisk(supplierId: SupplierId): Promise<bigint>;
    computeQualityRisk(supplierId: SupplierId): Promise<bigint>;
    getCompositeRisk(supplierId: SupplierId): Promise<bigint>;
    getMitigationActions(supplierId: SupplierId): Promise<Array<MitigationAction>>;
    getPortfolioRiskSnapshot(): Promise<PortfolioRiskSnapshot>;
    getRecommendedAlternatives(supplierId: SupplierId, category: SupplierCategory): Promise<Array<AlternativeSupplier>>;
    getRiskAlerts(threshold: bigint): Promise<Array<RiskAlert>>;
    getSupplierProfiles(): Promise<Array<SupplierProfile>>;
    getSupplierTrendHistory(supplierId: SupplierId, days: bigint): Promise<Array<RiskTrendEntry>>;
    getSupplyNetworkGraph(): Promise<SupplyNetworkGraph>;
    logMitigationAction(supplierId: SupplierId, action: string, dueDate: Timestamp): Promise<bigint>;
    simulateDisruption(supplierId: SupplierId, disruptionType: DisruptionType): Promise<DisruptionImpact>;
    updateSupplierMetrics(supplierId: SupplierId, metrics: SupplierMetricsUpdate): Promise<boolean>;
}
import type { AlternativeSupplier as _AlternativeSupplier, DisruptionImpact as _DisruptionImpact, DisruptionType as _DisruptionType, MitigationAction as _MitigationAction, MitigationStatus as _MitigationStatus, NetworkNode as _NetworkNode, RiskAlert as _RiskAlert, RiskLevel as _RiskLevel, RiskScore as _RiskScore, SupplierCategory as _SupplierCategory, SupplierId as _SupplierId, SupplierMetricsUpdate as _SupplierMetricsUpdate, SupplierProfile as _SupplierProfile, SupplierTier as _SupplierTier, SupplyNetworkGraph as _SupplyNetworkGraph, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async computeDelayRisk(arg0: SupplierId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.computeDelayRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeDelayRisk(arg0);
            return result;
        }
    }
    async computeFailureRisk(arg0: SupplierId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.computeFailureRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeFailureRisk(arg0);
            return result;
        }
    }
    async computeQualityRisk(arg0: SupplierId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.computeQualityRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeQualityRisk(arg0);
            return result;
        }
    }
    async getCompositeRisk(arg0: SupplierId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompositeRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompositeRisk(arg0);
            return result;
        }
    }
    async getMitigationActions(arg0: SupplierId): Promise<Array<MitigationAction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMitigationActions(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMitigationActions(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioRiskSnapshot(): Promise<PortfolioRiskSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioRiskSnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioRiskSnapshot();
            return result;
        }
    }
    async getRecommendedAlternatives(arg0: SupplierId, arg1: SupplierCategory): Promise<Array<AlternativeSupplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedAlternatives(arg0, to_candid_SupplierCategory_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedAlternatives(arg0, to_candid_SupplierCategory_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskAlerts(arg0: bigint): Promise<Array<RiskAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskAlerts(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskAlerts(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierProfiles(): Promise<Array<SupplierProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierProfiles();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierProfiles();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierTrendHistory(arg0: SupplierId, arg1: bigint): Promise<Array<RiskTrendEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierTrendHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierTrendHistory(arg0, arg1);
            return result;
        }
    }
    async getSupplyNetworkGraph(): Promise<SupplyNetworkGraph> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplyNetworkGraph();
                return from_candid_SupplyNetworkGraph_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplyNetworkGraph();
            return from_candid_SupplyNetworkGraph_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMitigationAction(arg0: SupplierId, arg1: string, arg2: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logMitigationAction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMitigationAction(arg0, arg1, arg2);
            return result;
        }
    }
    async simulateDisruption(arg0: SupplierId, arg1: DisruptionType): Promise<DisruptionImpact> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateDisruption(arg0, to_candid_DisruptionType_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_DisruptionImpact_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateDisruption(arg0, to_candid_DisruptionType_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_DisruptionImpact_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplierMetrics(arg0: SupplierId, arg1: SupplierMetricsUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplierMetrics(arg0, to_candid_SupplierMetricsUpdate_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplierMetrics(arg0, to_candid_SupplierMetricsUpdate_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlternativeSupplier_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlternativeSupplier): AlternativeSupplier {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DisruptionImpact_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionImpact): DisruptionImpact {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_DisruptionType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionType): DisruptionType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_MitigationAction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MitigationAction): MitigationAction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MitigationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MitigationStatus): MitigationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_NetworkNode_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NetworkNode): NetworkNode {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RiskAlert_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskAlert): RiskAlert {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierCategory): SupplierCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierProfile): SupplierProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierTier_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierTier): SupplierTier {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SupplyNetworkGraph_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplyNetworkGraph): SupplyNetworkGraph {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rank: bigint;
    tier: _SupplierTier;
    compositeRisk: _RiskScore;
    avgLeadTimeDays: bigint;
    category: _SupplierCategory;
    supplierId: _SupplierId;
}): {
    name: string;
    rank: bigint;
    tier: SupplierTier;
    compositeRisk: RiskScore;
    avgLeadTimeDays: bigint;
    category: SupplierCategory;
    supplierId: SupplierId;
} {
    return {
        name: value.name,
        rank: value.rank,
        tier: from_candid_SupplierTier_n11(_uploadFile, _downloadFile, value.tier),
        compositeRisk: value.compositeRisk,
        avgLeadTimeDays: value.avgLeadTimeDays,
        category: from_candid_SupplierCategory_n13(_uploadFile, _downloadFile, value.category),
        supplierId: value.supplierId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qualityRisk: _RiskScore;
    delayRisk: _RiskScore;
    supplierName: string;
    compositeRisk: _RiskScore;
    triggeredAt: _Timestamp;
    failureRisk: _RiskScore;
    riskLevel: _RiskLevel;
    supplierId: _SupplierId;
}): {
    qualityRisk: RiskScore;
    delayRisk: RiskScore;
    supplierName: string;
    compositeRisk: RiskScore;
    triggeredAt: Timestamp;
    failureRisk: RiskScore;
    riskLevel: RiskLevel;
    supplierId: SupplierId;
} {
    return {
        qualityRisk: value.qualityRisk,
        delayRisk: value.delayRisk,
        supplierName: value.supplierName,
        compositeRisk: value.compositeRisk,
        triggeredAt: value.triggeredAt,
        failureRisk: value.failureRisk,
        riskLevel: from_candid_RiskLevel_n18(_uploadFile, _downloadFile, value.riskLevel),
        supplierId: value.supplierId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SupplierId;
    carrierPerformanceScore: number;
    defectRate: number;
    dependsOn: Array<_SupplierId>;
    qualityRisk: bigint;
    yearsActive: bigint;
    delayRisk: bigint;
    name: string;
    onTimeDeliveryRate: number;
    tier: _SupplierTier;
    volumeHandled: bigint;
    compositeRisk: bigint;
    equipmentFailureRate: number;
    avgLeadTimeDays: bigint;
    category: _SupplierCategory;
    supplyInterruptionCount: bigint;
    failureRisk: bigint;
    location: string;
}): {
    id: SupplierId;
    carrierPerformanceScore: number;
    defectRate: number;
    dependsOn: Array<SupplierId>;
    qualityRisk: bigint;
    yearsActive: bigint;
    delayRisk: bigint;
    name: string;
    onTimeDeliveryRate: number;
    tier: SupplierTier;
    volumeHandled: bigint;
    compositeRisk: bigint;
    equipmentFailureRate: number;
    avgLeadTimeDays: bigint;
    category: SupplierCategory;
    supplyInterruptionCount: bigint;
    failureRisk: bigint;
    location: string;
} {
    return {
        id: value.id,
        carrierPerformanceScore: value.carrierPerformanceScore,
        defectRate: value.defectRate,
        dependsOn: value.dependsOn,
        qualityRisk: value.qualityRisk,
        yearsActive: value.yearsActive,
        delayRisk: value.delayRisk,
        name: value.name,
        onTimeDeliveryRate: value.onTimeDeliveryRate,
        tier: from_candid_SupplierTier_n11(_uploadFile, _downloadFile, value.tier),
        volumeHandled: value.volumeHandled,
        compositeRisk: value.compositeRisk,
        equipmentFailureRate: value.equipmentFailureRate,
        avgLeadTimeDays: value.avgLeadTimeDays,
        category: from_candid_SupplierCategory_n13(_uploadFile, _downloadFile, value.category),
        supplyInterruptionCount: value.supplyInterruptionCount,
        failureRisk: value.failureRisk,
        location: value.location
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    edgeCount: bigint;
    nodes: Array<_NetworkNode>;
}): {
    edgeCount: bigint;
    nodes: Array<NetworkNode>;
} {
    return {
        edgeCount: value.edgeCount,
        nodes: from_candid_vec_n25(_uploadFile, _downloadFile, value.nodes)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dependsOn: Array<_SupplierId>;
    supplierName: string;
    tier: _SupplierTier;
    compositeRisk: _RiskScore;
    category: _SupplierCategory;
    supplierId: _SupplierId;
}): {
    dependsOn: Array<SupplierId>;
    supplierName: string;
    tier: SupplierTier;
    compositeRisk: RiskScore;
    category: SupplierCategory;
    supplierId: SupplierId;
} {
    return {
        dependsOn: value.dependsOn,
        supplierName: value.supplierName,
        tier: from_candid_SupplierTier_n11(_uploadFile, _downloadFile, value.tier),
        compositeRisk: value.compositeRisk,
        category: from_candid_SupplierCategory_n13(_uploadFile, _downloadFile, value.category),
        supplierId: value.supplierId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MitigationStatus;
    action: string;
    createdAt: _Timestamp;
    dueDate: _Timestamp;
    updatedAt: _Timestamp;
    supplierId: _SupplierId;
}): {
    id: bigint;
    status: MitigationStatus;
    action: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    updatedAt: Timestamp;
    supplierId: SupplierId;
} {
    return {
        id: value.id,
        status: from_candid_MitigationStatus_n4(_uploadFile, _downloadFile, value.status),
        action: value.action,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        updatedAt: value.updatedAt,
        supplierId: value.supplierId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimatedRecoveryDays: bigint;
    cascadingSupplierIds: Array<_SupplierId>;
    affectedSupplierId: _SupplierId;
    directRiskIncrease: bigint;
    disruptionType: _DisruptionType;
    portfolioRiskDelta: bigint;
    severity: _RiskLevel;
}): {
    estimatedRecoveryDays: bigint;
    cascadingSupplierIds: Array<SupplierId>;
    affectedSupplierId: SupplierId;
    directRiskIncrease: bigint;
    disruptionType: DisruptionType;
    portfolioRiskDelta: bigint;
    severity: RiskLevel;
} {
    return {
        estimatedRecoveryDays: value.estimatedRecoveryDays,
        cascadingSupplierIds: value.cascadingSupplierIds,
        affectedSupplierId: value.affectedSupplierId,
        directRiskIncrease: value.directRiskIncrease,
        disruptionType: from_candid_DisruptionType_n32(_uploadFile, _downloadFile, value.disruptionType),
        portfolioRiskDelta: value.portfolioRiskDelta,
        severity: from_candid_RiskLevel_n18(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Tier1: null;
} | {
    Tier2: null;
} | {
    Tier3: null;
}): SupplierTier {
    return "Tier1" in value ? SupplierTier.Tier1 : "Tier2" in value ? SupplierTier.Tier2 : "Tier3" in value ? SupplierTier.Tier3 : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Chemicals: null;
} | {
    RawMaterials: null;
} | {
    Packaging: null;
} | {
    Logistics: null;
} | {
    Services: null;
} | {
    Electronics: null;
} | {
    Manufacturing: null;
}): SupplierCategory {
    return "Chemicals" in value ? SupplierCategory.Chemicals : "RawMaterials" in value ? SupplierCategory.RawMaterials : "Packaging" in value ? SupplierCategory.Packaging : "Logistics" in value ? SupplierCategory.Logistics : "Services" in value ? SupplierCategory.Services : "Electronics" in value ? SupplierCategory.Electronics : "Manufacturing" in value ? SupplierCategory.Manufacturing : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): RiskLevel {
    return "Low" in value ? RiskLevel.Low : "High" in value ? RiskLevel.High : "Medium" in value ? RiskLevel.Medium : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    QualityFailure: null;
} | {
    LogisticsDelay: null;
} | {
    SupplyInterruption: null;
} | {
    NaturalDisaster: null;
} | {
    EquipmentFailure: null;
}): DisruptionType {
    return "QualityFailure" in value ? DisruptionType.QualityFailure : "LogisticsDelay" in value ? DisruptionType.LogisticsDelay : "SupplyInterruption" in value ? DisruptionType.SupplyInterruption : "NaturalDisaster" in value ? DisruptionType.NaturalDisaster : "EquipmentFailure" in value ? DisruptionType.EquipmentFailure : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Cancelled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): MitigationStatus {
    return "Open" in value ? MitigationStatus.Open : "Cancelled" in value ? MitigationStatus.Cancelled : "InProgress" in value ? MitigationStatus.InProgress : "Completed" in value ? MitigationStatus.Completed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MitigationAction>): Array<MitigationAction> {
    return value.map((x)=>from_candid_MitigationAction_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskAlert>): Array<RiskAlert> {
    return value.map((x)=>from_candid_RiskAlert_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupplierProfile>): Array<SupplierProfile> {
    return value.map((x)=>from_candid_SupplierProfile_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NetworkNode>): Array<NetworkNode> {
    return value.map((x)=>from_candid_NetworkNode_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlternativeSupplier>): Array<AlternativeSupplier> {
    return value.map((x)=>from_candid_AlternativeSupplier_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DisruptionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): _DisruptionType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SupplierCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierCategory): _SupplierCategory {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SupplierMetricsUpdate_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierMetricsUpdate): _SupplierMetricsUpdate {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carrierPerformanceScore?: number;
    defectRate?: number;
    onTimeDeliveryRate?: number;
    volumeHandled?: bigint;
    equipmentFailureRate?: number;
    avgLeadTimeDays?: bigint;
    supplyInterruptionCount?: bigint;
}): {
    carrierPerformanceScore: [] | [number];
    defectRate: [] | [number];
    onTimeDeliveryRate: [] | [number];
    volumeHandled: [] | [bigint];
    equipmentFailureRate: [] | [number];
    avgLeadTimeDays: [] | [bigint];
    supplyInterruptionCount: [] | [bigint];
} {
    return {
        carrierPerformanceScore: value.carrierPerformanceScore ? candid_some(value.carrierPerformanceScore) : candid_none(),
        defectRate: value.defectRate ? candid_some(value.defectRate) : candid_none(),
        onTimeDeliveryRate: value.onTimeDeliveryRate ? candid_some(value.onTimeDeliveryRate) : candid_none(),
        volumeHandled: value.volumeHandled ? candid_some(value.volumeHandled) : candid_none(),
        equipmentFailureRate: value.equipmentFailureRate ? candid_some(value.equipmentFailureRate) : candid_none(),
        avgLeadTimeDays: value.avgLeadTimeDays ? candid_some(value.avgLeadTimeDays) : candid_none(),
        supplyInterruptionCount: value.supplyInterruptionCount ? candid_some(value.supplyInterruptionCount) : candid_none()
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): {
    QualityFailure: null;
} | {
    LogisticsDelay: null;
} | {
    SupplyInterruption: null;
} | {
    NaturalDisaster: null;
} | {
    EquipmentFailure: null;
} {
    return value == DisruptionType.QualityFailure ? {
        QualityFailure: null
    } : value == DisruptionType.LogisticsDelay ? {
        LogisticsDelay: null
    } : value == DisruptionType.SupplyInterruption ? {
        SupplyInterruption: null
    } : value == DisruptionType.NaturalDisaster ? {
        NaturalDisaster: null
    } : value == DisruptionType.EquipmentFailure ? {
        EquipmentFailure: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierCategory): {
    Chemicals: null;
} | {
    RawMaterials: null;
} | {
    Packaging: null;
} | {
    Logistics: null;
} | {
    Services: null;
} | {
    Electronics: null;
} | {
    Manufacturing: null;
} {
    return value == SupplierCategory.Chemicals ? {
        Chemicals: null
    } : value == SupplierCategory.RawMaterials ? {
        RawMaterials: null
    } : value == SupplierCategory.Packaging ? {
        Packaging: null
    } : value == SupplierCategory.Logistics ? {
        Logistics: null
    } : value == SupplierCategory.Services ? {
        Services: null
    } : value == SupplierCategory.Electronics ? {
        Electronics: null
    } : value == SupplierCategory.Manufacturing ? {
        Manufacturing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
